### ISSUE TITLE
[BUG]  date changes unintended

### ISSUE THREAD

**Issue by devii21** [kfiross/flutter_holo_date_picker#15]
When changing the year, sometimes the month gets changed to a seemingly random month. Same with month/day.

To reproduce:
```
        DatePickerWidget(
            initialDate: DateTime.now(),
            firstDate: DateTime.now(),
            onChange: (value, _) {
              print(value.toString());
            }),
```

- select next month   (Dec)
- select next year   (2021)
-> february gets selected

OR

- select next month (Dec)
- select first
- select current month (Nov)
-> 9th gets selected

**Comment by kfiross** [comment]
Hi, I'll look for it

**Comment by shabeenabarde** [comment]
I am facing the same issue. But if i change my initial date from **DateTime.now()**. to lets say **DateTime(2020)**, it works fine. But I do not want that because I do not want my users to be able to select back dates.

But when it is selected as DateTime.now(), and I select **Dec 28th 2020**, It Gives me the date of **Dec 3rd, 2020**...

**Comment by kfiross** [comment]
If I got it right, when you change the month - the day is selected "randomly"?

**Comment by kfiross** [comment]
@devii21 @shabeenabarde I uploaded a dev version, please check it and tell if the bug is fixed/

**Comment by shabeenabarde** [comment]
@kfiross I changed my channel to Dev, and the issue still persists. I don't know if i am going wrong somewhere.

This is my flutter doctor Summary:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.4)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)
    ! Error: Shabeena’s iPhone is not connected. Xcode will continue when Shabeena’s iPhone is connected. (code -13)

**Comment by kfiross** [comment]
@shabeenabarde  I meant the fix should be fixed in 0.3.0-dev

**Comment by shabeenabarde** [comment]
@kfiross It works fine with ^0.3.0-dev.1

**Comment by kfiross** [comment]
@shabeenabarde thanks! Issue closed.

**Comment by shabeenabarde** [comment]
@kfiross 

Kindly find the code below, I am facing a similar issue again:
`
import 'package:flutter/material.dart';
import 'package:flutter_holo_date_picker/flutter_holo_date_picker.dart';
import 'package:intl/intl.dart';

class DateTestingTwo extends StatefulWidget {
  DateTestingTwo({Key key}) : super(key: key);

  @override
  _DateTestingTwoState createState() => _DateTestingTwoState();
}

class _DateTestingTwoState extends State<DateTestingTwo> {
  static DateTime startDate = DateTime.now();
  String quoteStartDate = DateFormat.yMMMd().format(startDate);
  String endPeriod = DateFormat.yMMMd()
      .format(DateTime.now().add(Duration(days: 2)))
      .toString();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(
            "Date Testing 2",
          ),
        ),
        body: ListView(
          children: [
            RaisedButton(
              child: Text("$quoteStartDate"),
              onPressed: () async {
                try {
                  var selectedFirstDate = await DatePicker.showSimpleDatePicker(
                    context,
                    initialDate: DateFormat.yMMMd().parse(quoteStartDate),
                    firstDate: DateTime.now(),
                    lastDate: DateTime(2030),
                    dateFormat: "yyyy-MMMM-dd",
                    locale: DateTimePickerLocale.en_us,
                    looping: true,
                  );

                  print("My date is picked $selectedFirstDate");

                  setState(() {
                    setState(() {
                      quoteStartDate =
                          DateFormat.yMMMd().format(selectedFirstDate);

                      print("My quoteStartDate is picked $quoteStartDate");
                    });
                  });
                } catch (e) {
                  print("My error is $e");
                }
              },
            ),
            RaisedButton(
              child: Text("$endPeriod"),
              onPressed: () async {
                try {
                  var selectedEndDate = await DatePicker.showSimpleDatePicker(
                    context,
                    initialDate: DateFormat.yMMMd().parse(endPeriod),
                    firstDate: DateFormat.yMMMd()
                        .parse(quoteStartDate)
                        .subtract(Duration(days: 0)),
                    lastDate: DateFormat.yMMMd()
                        .parse(quoteStartDate)
                        .add(Duration(days: 30)),
                    dateFormat: "yyyy-MMMM-dd",
                    locale: DateTimePickerLocale.en_us,
                    looping: true,
                  );

                  setState(() {
                    endPeriod =
                        DateFormat.yMMMd().format(selectedEndDate).toString();
                  });

                  print("My date is picked $selectedEndDate");
                } catch (e) {
                  print("My error is $e");
                }
              },
            ),
          ],
        ));
  }
}
`

Lets say my $quoteStartDate is 6th Dec 2020. So when i am choosing my $endPeriod, I want the firstDate of the $endPeriod to not go below the $quoteStartDate so I have set the firstDate for the $endPeriod to $quoteStartDate. So when i am choosing 6th Dec 2020 for $endPeriod, it automatically chooses 7th Dec 2020, I want it to be 6th Dec 2020 as selected. Why is that? I want the user to be able to select the $quoteStartDate and the $quoteEndDate as the same day.
