### ISSUE TITLE
Month text losing form on smaller screens

### ISSUE THREAD

**Issue by SidneyMachara** [kfiross/flutter_holo_date_picker#19]
<img width="262" alt="Screenshot 2020-12-18 at 11 09 26" src="https://user-images.githubusercontent.com/16288678/102596197-81a91480-4121-11eb-982e-2508d10a4652.png">

the text should resized on smaller screens

**Comment by kfiross** [comment]
Hi! I will make a fix soon, can you tell me on which device you tried? (screen size)

**Comment by kfiross** [comment]
@SidneyMachara Can you check if the git version work correctly?

**Comment by SidneyMachara** [comment]
> Hi! I will make a fix soon, can you tell me on which device you tried? (screen size)

@kfiross its was on this device --> OPPO A5.

we ended up using the DatePickerWidget provided by the package then  rescaling the text in DateTimePickerTheme based in device height.

**Comment by kfiross** [comment]
@SidneyMachara  I'm just added auto_text_size support so you don't have to set the font by calculations, so I wanted to know if it's fixed with it

**Comment by SidneyMachara** [comment]
@kfiross unfortunately i dont have a small device anymore to test on, But i believe  auto_text_size will solve the issue.
ill be sure to give feedback the next time i run into a small device.
