### ISSUE TITLE
day 1 is not recognized

### ISSUE THREAD

**Issue by mahdi-ko** [kfiross/flutter_holo_date_picker#22]
when using the `DatePickerWidget`  and scrolling the day column to the value 1, `onChange ` is not triggered and scrolling the month will revert the day value to the last day chosen before 1,
deleting the lines 308-309 of the file [date_picker_widget.dart](https://github.com/kfiross/flutter_holo_date_picker/blob/master/lib/widget/date_picker_widget.dart) solves the issue, but I don't know if it have side effects.

**Comment by STG284** [comment]
I am also facing this issue

**Comment by kfiross** [comment]
Hi, sorry for the late response
I'll will iron out it asap

**Comment by mahdi-ko** [comment]
no worries, thanks.

**Comment by JErazo7** [comment]
In flutter_holo_date_picker 1.0.0-nullsafety.1 this bug persist, check please

**Comment by kfiross** [comment]
@JErazo7 I'll re-check the issue
