### ISSUE TITLE
DatePicker returns null if current day is selected

### ISSUE THREAD

**Issue by STG284** [kfiross/flutter_holo_date_picker#26]
Steps to reproduce:
1. Open Dialog
`var picked = await DatePicker.showSimpleDatePicker(...)`
2. press "Ok" button
3. picked is `null`!

**Comment by kfiross** [comment]
@STG284  Sorry for the inconvenience, I'll check it soon

**Comment by kfiross** [comment]
The issue fixed in version 0.3.3
