### ISSUE TITLE
Any plans to support dart sound null safety feature

### ISSUE THREAD

**Issue by RR-Reddy** [kfiross/flutter_holo_date_picker#27]

**Comment by RR-Reddy** [comment]
here is pull #28  request

**Comment by kfiross** [comment]
@RR-Reddy Very appreciate the effort! thanks

**Comment by RR-Reddy** [comment]
@kfiross  please publish to pub.dev

**Comment by RR-Reddy** [comment]
Finally available in pub as pre release version  **flutter_holo_date_picker: 1.0.0-nullsafety.0**
