### ISSUE TITLE
Build fails on beta 1.17.0

### ISSUE THREAD

**Issue by tan-yaka** [kfiross/flutter_holo_date_picker#3]
On latest beta 1.17.0
```
Compiler message:                                                       
../../.pub-cache/hosted/pub.dartlang.org/flutter_holo_date_picker-0.1.2+6/lib/date_picker_theme.dart:43:9: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  const DateTimePickerTheme({                                           
        ^^^^^^^^^^^^^^^^^^^                                             
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.
``` 

`class DateTimePickerTheme extends Diagnosticable`

should be 

`class DateTimePickerTheme with Diagnosticable`

**Comment by kfiross** [comment]
is a problem related for flutter 1.17.* changes? because it work good on beta 1.15.17

**Comment by tan-yaka** [comment]
Must be because it was building fine for me with the previous beta. I'll have a look at the changelog when I get a chance

**Comment by tan-yaka** [comment]
Looks like Diagnosticable is now a mixin:

https://github.com/flutter/flutter/issues/50498

Suggested fix:

https://github.com/dylanwuzh/flutter-cupertino-date-picker/pull/86

**Comment by kfiross** [comment]
Thank you very much! Update with the fix will uploaded soon.
