### ISSUE TITLE
chinese locale zh_cn isn't applying 

### ISSUE THREAD

**Issue by abdulShanti** [kfiross/flutter_holo_date_picker#41]

**Comment by abdulShanti** [comment]
`DatePickerWidget(
                                    locale: locale == 'zh'
                                        ? DateTimePickerLocale.zh_cn
                                        : DateTimePickerLocale.en_us,
                                    lastDate: DateTime.now(),
                                    // dateFormat: "yyyy : MMM : dd",
                                    dateFormat: 'yyyy MMMM dd',
                                    onChange: (DateTime newDate, _) {
                                      setState(() {
                                        dob = newDate.toString();
                                        print(dob);
                                      });
                                    },
                                    pickerTheme: DateTimePickerTheme(
                                      backgroundColor: Colors.transparent,
                                      dividerColor: const Color(0xffe3e3e3),
                                      itemTextStyle: TextStyle(
                                        fontFamily: 'NotoSansTC',
                                        fontSize: 18,
                                        fontWeight: FontWeight.w500,
                                        color: Theme.of(context).primaryColor,
                                      ),
                                    ),
                                  ),`

**Comment by kfiross** [comment]
Hi @abdulShanti 
I'll check why it's doesn't applying

**Comment by kfiross** [comment]
![image](https://user-images.githubusercontent.com/19295474/157128025-6e118a36-354e-4e1b-9dc6-b387c6420eff.png)

That's why..
