### ISSUE TITLE
Incorrect month selected not same on picker display

### ISSUE THREAD

**Issue by kullawattana** [kfiross/flutter_holo_date_picker#55]
I have found an issue first step check current date is 18 August 2022. It shows that "2022-08-18" is correct.
and the second step I selected was 18 August 2023. It shows that "2023-05-18" is not correct. 
@kfiross 

https://user-images.githubusercontent.com/3391151/185331099-f4cbe7db-f455-4dc1-9e20-d9e3c998f5a6.mov

**Comment by kullawattana** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-TH)
    • Flutter version 3.0.5 at /Users/akarapon/Documents/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Comment by kfiross** [comment]
fixed at #53 !
