### ISSUE TITLE
named parameter "primary" is not available for TextButton.styleFrom in flutter version 3.19.5

### ISSUE THREAD

**Issue by kishanatpl** [kfiross/flutter_holo_date_picker#67]
../../.pub-cache/hosted/pub.dev/flutter_holo_date_picker-1.1.0/lib/date_picker.dart:132:37: Error: No named parameter with the name 'primary'.
        style: TextButton.styleFrom(primary: textColor),

upgradation is required as per new flutter version

**Comment by kfiross** [comment]
@kishanatpl will be fixed in v2.0.0
