### ISSUE TITLE
DiagnosticableMixin is officially deprecated !

### ISSUE THREAD

**Issue by mohanadshaban** [kfiross/flutter_holo_date_picker#7]
After Flutter 1.20 DiagnosticableMixin is officially deprecated. 
So i cannot use the library and i get this error 

>  Error: Type 'DiagnosticableMixin' not found.
class DateTimePickerTheme with DiagnosticableMixin {
                                                    ^^^^^^^^^^^^^^

I believe you just need to remove "with DiagnosticableMixin" that will fix the issue 

Thanks in Advance

**Comment by rmsh03dhj** [comment]
Facing same problem. 

class DateTimePickerTheme with DiagnosticableMixin {
                                                         ^^^^^^^^^^^^^^^^^^^

Error: The type 'DiagnosticableMixin' can't be mixed in.

Found suggestion to replace 'DiagnosticableMixin' with 'Diagnosticable'. It fixes the issue on local machine. 
Facing issue while building app for deployment. 

Thanks

**Comment by pradt** [comment]
Yup same, just had to upgrade :/

**Comment by endruszeit** [comment]
Same issue here. Saw the pull request is already there. Would appreciate if it's merged soon.

**Comment by kfiross** [comment]
Sorry for the late response, I'll fix it today

**Comment by kfiross** [comment]
Merged PR and updated package, Issue Closed
